// web/src/common/molecules/BottomSheet.vue
<script lang="ts" setup>
const emit = defineEmits<{
  closeSheet: []
}>()

const closeSheet = () => {
  emit('closeSheet')
}
</script>

<template>
  <div class="fixed inset-0 bg-black/50 bg-opacity-50 z-10" @click="closeSheet"></div>

  <div class="fixed bottom-0 min-h-20 left-0 right-0 bg-slate-900 z-20 border-t border-slate-600">
    <div class="flex justify-center p-2">
      <button
        @click="closeSheet"
        class="w-12 h-2 bg-slate-600 cursor-pointer rounded-full"
      ></button>
    </div>

    <div class="p-4 flex flex-col gap-4">
      <slot />
    </div>
  </div>
</template>

// web/src/common/molecules/bottom-sheet.tsx
import type { ReactNode } from 'react'

interface BottomSheetProps {
  onClose: () => void
  children: ReactNode
}

export function BottomSheet(p: BottomSheetProps) {
  return (
    <div className='fixed inset-0 w-dvw h-dvh z-10'>
      <button
        type='button'
        className='fixed z-20 inset-0 w-dvw h-dvh bg-black/50'
        onClick={p.onClose}
      />

      <div className='fixed z-30 bottom-0 left-0 right-0 max-h-[80dvh] overflow-y-auto bg-mist-900 flex flex-col'>
        {p.children}
      </div>
    </div>
  )
}
