// new-web/src/routes/apps/todos/(home)/-header.tsx
import { btn } from "#/common/atoms/btn"
import { FunnelIcon, HouseIcon } from "@phosphor-icons/react"
import { Link } from "@tanstack/react-router"

export function Header({}: {}) {
  return (
    <header className="flex items-center justify-between gap-2 border-b-2 border-mist-300 dark:border-mist-800 p-2">
      <Link to="/" className={btn({ isIcon: true })}>
        <HouseIcon size={24} />
      </Link>

      <p className="text-sky-500 font-bold text-lg">Todos</p>

      <button disabled className={btn({ isIcon: true })}>
        <FunnelIcon size={24} />
      </button>
    </header>
  )
}

// web/src/views/home/Header.vue
<script lang="ts" setup>
const props = defineProps<{
  version: number
}>()
</script>

<template>
  <header class="flex flex-col items-center gap-2">
    <img src="/fanoos.png" class="size-16 rounded-md" />

    <p class="flex gap-1 items-center">
      <span class="text-2xl font-bold text-sky-500">Fanoos</span>
      <sup>v{{ version }}</sup>
    </p>
  </header>
</template>
